import streamlit as st

from _layout import render_home_header, render_page_footer

st.set_page_config(page_title="OULAD-Lite LA Dashboard", layout="wide")

render_home_header()

st.write(
    "This proof-of-concept is built by Hugo Li together with Cursor (an agentic AI tool). "
    "It explores some state-of-the-art design principles for learning analytics dashboards "
    "(LAD): adaptive for teacher agency, encouraging student self-regulated learning "
    "(SRL), subject-domain-specific considerations, and honest limits on what clickstream "
    "data cannot say. Beyond that, based on Hugo Li's former fieldwork, master's studies, "
    "and doctoral research, it tries to apply critical theories from the history and "
    "philosophy of education in designing LAD. It is not a claim to ML expertise."
)

st.subheader("Data source")
st.markdown(
    "Built on the [Open University Learning Analytics Dataset]"
    "(https://analyse.kmi.open.ac.uk/open-dataset) "
    "(OULAD, Kuzilek et al. 2017, CC-BY 4.0). This demo uses modules **BBB** "
    "(humanities) and **DDD** (STEM) with all features computed at **day 28** — "
    "no post-hoc leakage from later weeks."
)

st.subheader("Three special design choices")

with st.expander("A. Adaptive LA for teacher agency (and digital capability)", expanded=True):
    st.write(
        "Three info groups (What is / What's behind / What next) collapse independently "
        "per teacher's preference. A Hide model predictions toggle lets a teacher use "
        "the dashboard without algorithmic suggestion."
    )
    st.caption(
        "Lapage, Crabbé, & Depaepe (2026) argue that teachers prefer dashboards that "
        "support—not replace—instructional autonomy, and call for adaptable designs across "
        "changing needs, contexts, and teaching phases (preparation, delivery, reflection). "
        "Van Leeuwen & Rummel (2020) frame a division of responsibility: in advisory mode "
        "the system carries initial assessment while the teacher judges whether suggestions "
        "are reasonable, easing cognitive load and strengthening decision confidence. "
        "Collapsible What is / What's behind / What next sections and the Hide model "
        "predictions toggle embody this stance, including Depaepe-style deliberate non-use.",
    )

with st.expander("B. Teacher community of practice", expanded=True):
    st.write(
        "When a teacher is concerned about a student, they can convene a case conference — "
        "but the student must be informed and may attend. Teachers also share daily-life "
        "moments on a separate timeline."
    )
    st.caption(
        "Reframes 'cross-teacher alert' (a surveillance pattern) into multi-stakeholder "
        "dialogue (Tinto 1993 academic+social integration; Wenger 1998 communities of "
        "practice). The student-present check is a deliberate ethical constraint "
        "(Slade & Prinsloo 2013 on LA ethical dilemmas; Prinsloo & Slade 2014 on "
        "intrusion, surveillance, and care). Hugo Li's doctoral research in the history "
        "of education reform likewise emphasises teacher networking and professional "
        "community as drivers of individual development.",
    )

with st.expander("C. Student data-erasure as pedagogical right", expanded=True):
    st.write(
        "Each semester, a student may request erasure of fine-grained behavioral data. "
        "The teacher is informed and may negotiate, but the student decides."
    )
    st.caption(
        "Implements Masschelein & Simons (2013) scholè — school as a place that releases "
        "students from their predefined (past) records — within an LA system. "
        "Simons & Masschelein (2021) also argue that students should always have the right "
        "to begin anew, free from predefined persona generated by algorithmic tracking. "
        "Consistent with data-subject rights under GDPR-style frameworks, implemented here "
        "as a pedagogical principle: enabling a fresh-start opportunity for the learner. "
        "Erasable: clickstream. Non-erasable: assessment results, registration. Students "
        "see what was cleared; teachers can preview model effect in Data erasure "
        "(educator view).",
    )

st.subheader("How to read this demo")
st.write(
    "Use the sidebar to open **Teacher BBB**, **Teacher DDD**, and the "
    "**Student** view. Compare how the two teacher dashboards differ in thresholds, "
    "signals, and discussion prompts while sharing the same underlying model."
)

with st.expander("Honest limitations", expanded=False):
    st.markdown(
        """
- **Day-28 features only** — the model never sees behaviour or assessments after week 4.
- **No TMA text content** — only scores and submission timing, not what students wrote.
- **No real teacher–student dialog data** — contact flows are mocked for layout only.
- **Clickstream** — a behavioural proxy only, not engagement quality.
        """
    )
    st.caption(
        "Footnote: VLE clicks log activity, not self-regulated learning "
        "(Zimmerman 2002; Panadero 2017)."
    )

with st.expander("What this demo does NOT collect", expanded=False):
    st.write(
        "No forum post text content; no facial / camera data; no emotion or affect "
        "recognition; no behavioural data beyond the platform clickstream that OULAD "
        "itself contains. The data-minimisation principle constrains what predictive "
        "models can plausibly say."
    )

render_page_footer()
